Host: 0.0.0.0  # IP address the application will listen on
Port: 8080  # Port for the application
Debug: true  # Enable debug mode

Logger:
  File: ./ppanel.log  # Log file path
  Level: production  # Log level: info, debug, error, production

JwtAuth:
  AccessSecret: 333ab3d5-429f-4a51-b001-ef484bf11db7  # Token secret (should be changed)
  AccessExpire: 604800  # Token expiration time in seconds

MySQL:
  Path: 127.0.0.1  # Database address
  Port: 3306  # Database port
  Dbname: vpnboard  # Database name
  Username: root  # Database username
  Password:  # Database password
  MaxIdleConns: 10  # Maximum idle connections
  MaxOpenConns: 10  # Maximum open connections
  LogMode: "dev"  # Log mode
  LogZap: false  # Enable Zap logger
  Config: charset=utf8mb4&parseTime=true&loc=Asia%2FShanghai  # Database config parameters

Redis:
  Host: 127.0.0.1:6379  # Redis server address
  Type: server  # Redis type
  Pass:  # Redis password (if any)
